version: '3.8'
services:
  api:
    build: ./backend
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/rehearsal
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rehearsal
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
volumes:
  pgdata: